[build]
  command = "npm ci --production"
  functions = "functions"
  publish = "."

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["functions/server.js"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
